### ISSUE TITLE
Addon conflict

### ISSUE THREAD

**Issue by Daeymien** [melroy999/RareTrackerCore#6]
With the 2.x rewrite/revamp, RareTracker silently fails to load if **Warfront Rare Tracker** `https://www.curseforge.com/wow/addons/warfront-rare-tracker` is loaded simultaneously.

**Comment by melroy999** [comment]
Curious. I suppose the addon uses the same internal addon name "RareTracker"... Thanks for the heads-up!

**Comment by melroy999** [comment]
Ah I see... this is actually caused by a piece of deprecated code that has been changed in a more recent version that I will probably be releasing later today.

**Comment by melroy999** [comment]
This bug should be fixed in the latest (v2.0.8) release. Feel free to give me a warning if any issues persist!
